### ISSUE TITLE
Добавить первый уровень Level_1 унаследованный от LevelMap

### ISSUE THREAD

**Issue by bombermanrzn** [The-Bullfinch/LodeRunner#5]
- **Требуется создать первый уровень:**
- [x] Унаследоваться от LevelMap
- [x] Прикинуть и вынести общие черты для всех карт (их же будет несколько) в абстрактный класс LevelMap(сделать его абстрактным если это не так). Например я понимаю что любая карта будет представляться массивом (соответственно это поле в абстрактном классе) и метод parse
- [x] массив карты (составить карты и представить ее в виде двумерного массив символов, разные символа - разные виды блоков или персонажей)
- [x] Реализация метода parse. В цикле ты проходишь по массив и парсишь каждый знак на нужный объект
- [x] Перенести BlockType из StaticGameObject -> GameObject
- [x] Сделать Map<символ, BlockType> в levelMap (обязана содержать все BlockType и символ для каждого)
- [x] Метод parse() переделать с использованием Map из LevelMap и Map<String (BlockType.name()), GameObject>. Класть в мапу не GameObject,а соответствующего типа (GameStaticObject, Player и т.д.)

- **Реализовать тесты. Тест для проверки содержимого массива карты (отчасти реализован привести в порядок). Тест для функции parse** (в комментариях были описаны шаги)
- [x] Проверки на null, что коллекция объектов не пуста после выполнения и пр.
- [x] Соотношение количество каждого типа объекта с количеством символа в массиве
- [x] Проверить на необходимость создание тестов на изменение других классов

**Comment by QzVl** [comment]
Думаю в абстрактный класс можно вынести boolean поле уровень пройден или не пройден ?
